services:

  backend:
    image: ghcr.io/profomedia/orkobit-backend:latest

    container_name: orko_backend

    restart: unless-stopped

    # env_file:
    #   - /opt/ororklabs/orkobit/.env

    depends_on:
      - db
      - redis

    ports:
      - "8010:8000"

          # adding to caddy network called proxy
    networks:
      - default
      - proxy

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/admin/login/')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/profomedia/orkobit-frontend:latest

    container_name: orko_frontend
    ports:
      - "8030:80"

    restart: unless-stopped

    depends_on:
      - backend

    expose:
      - "80"
    
    # adding to caddy network called proxy
    networks:
      - default
      - proxy

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  worker:
    image: ghcr.io/profomedia/orkobit-backend:latest

    container_name: orko_worker

    restart: unless-stopped

    depends_on:
      - db
      - redis

    command: >
      celery -A config worker -l info

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres:16.4

    container_name: orko_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    image: redis:7.4

    container_name: orko_redis

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

    labels:
      - "com.centurylinklabs.watchtower.enable=false"


volumes:
  postgres_data:

