FROM node:22-alpine

# Set working directory
WORKDIR /app/frontend

# Copy package files first
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy frontend source
COPY frontend .

# Expose Vite port
EXPOSE 5173