# --------------------------------------------------
# BUILD STAGE
# --------------------------------------------------

FROM node:22-alpine AS builder

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend .

RUN npm run build

# --------------------------------------------------
# NGINX STAGE
# --------------------------------------------------

FROM nginx:alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]