# Generated by Django 6.0.4 on 2026-05-19 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('habit_type', models.CharField(choices=[('boolean', 'Boolean'), ('number', 'Number'), ('timer', 'Timer'), ('rating', 'Rating')], default='checkbox', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#7c5cff', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_type', models.CharField(choices=[('daily', 'Daily'), ('weekly_count', 'Weekly Count')], default='daily', max_length=20)),
                ('weekly_target', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='habit.habit')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['habit', 'date'], name='habit_habit_habit_i_08af21_idx'), models.Index(fields=['date'], name='habit_habit_date_791257_idx')],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
