# Generated by Django 6.0.4 on 2026-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='habitentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='habitentry',
            name='habit_habit_habit_i_08af21_idx',
        ),
        migrations.AddField(
            model_name='habitentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly_count', 'Weekly Count')], db_index=True, default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('number', 'Number'), ('timer', 'Timer'), ('rating', 'Rating')], db_index=True, default='boolean', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='habitentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['habit_type'], name='habit_habit_habit_t_3b0bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['frequency_type'], name='habit_habit_frequen_f202e5_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['is_archived'], name='habit_habit_is_arch_938807_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['position'], name='habit_habit_positio_9760b0_idx'),
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['habit', '-date'], name='habit_habit_habit_i_b18f45_idx'),
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['created_at'], name='habit_habit_created_df6c15_idx'),
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='completed',
        ),
    ]
