# Generated by Django 6.0.4 on 2026-05-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_options_alter_habitentry_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__gte', 0)), name='habit_target_value_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_target__gte', 1), ('weekly_target__isnull', True), _connector='OR'), name='habit_weekly_target_valid'),
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_entry_per_day'),
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 0), ('duration_seconds__isnull', True), _connector='OR'), name='habit_entry_duration_seconds_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.CheckConstraint(condition=models.Q(('value_number__gte', 0), ('value_number__isnull', True), _connector='OR'), name='habit_entry_value_number_gte_0'),
        ),
    ]
